name: Defines Options for SSC Actions
description: Defines Options for SSC Actions
author: 'Fortify'
runs:
#  using: composite
  steps:
    # Define options
    - id: ssc-options
      with:
        REPO_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      run: |
        # If not specified, set default AppVersion to octocat/Hello-World:branch
        if [ -z "$SSC_APPVERSION" ]; then 
          echo SSC_APPVERSION="${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}" >> $GITHUB_ENV
        fi
        # If not specified, set default FROM AppVersion to octocat/Hello-World:<defaul-branch>
        if [ -z "$SSC_APPVERSION_FROM" ]; then 
          if [ -n "$GITHUB_BASE_REF" ]; then
            echo SSC_APPVERSION_FROM="${GITHUB_REPOSITORY}:${GITHUB_BASE_REF}" >> $GITHUB_ENV
          elif [ -n "$REPO_DEFAULT_BRANCH" ]; then
            echo SSC_APPVERSION_FROM="${GITHUB_REPOSITORY}:${REPO_DEFAULT_BRANCH}" >> $GITHUB_ENV
          fi
        fi
      shell: bash
branding:
  icon: 'shield'
  color: 'blue'

